spring.application.name=football-booking

# server configuration
server.port=4000

# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/football_booking
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# jpa & flyway configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true